#!/usr/bin/env python3
"""Export a reviewed ProbCut TSV profile as constexpr C++ data."""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Iterable


MODE_CPP = {
    "move": "SearchMode::move",
    "analyze": "SearchMode::analyze",
    "exact_score": "SearchMode::exact_score",
    "win_loss_draw": "SearchMode::win_loss_draw",
}


class ExportError(ValueError):
    """Raised when the reviewed TSV cannot be exported exactly."""


def cpp_bool(value: str) -> str:
    if value not in {"true", "false"}:
        raise ExportError(f"invalid boolean: {value}")
    return value


def cpp_float(value: str) -> str:
    number = float(value)
    if not math.isfinite(number):
        raise ExportError(f"non-finite number: {value}")
    rendered = format(number, ".17g")
    return rendered if any(marker in rendered for marker in ".eE") else rendered + ".0"


def require_same(rows: list[dict[str, str]], field: str) -> str:
    values = {row[field] for row in rows}
    if len(values) != 1:
        raise ExportError(f"profile rows disagree on {field}")
    return next(iter(values))


def render(
    profile_path: Path,
    weights_checksum: str,
    maximum_margin: int,
    maximum_overhead: float,
) -> str:
    try:
        with profile_path.open(encoding="utf-8", newline="") as source:
            rows = list(csv.DictReader(source, delimiter="\t"))
    except (OSError, UnicodeDecodeError, csv.Error) as error:
        raise ExportError(f"cannot read profile: {error}") from error
    if not rows:
        raise ExportError("profile has no rows")
    if require_same(rows, "schema_version") != "3":
        raise ExportError("only schema-v3 profiles can be exported")
    if require_same(rows, "node_class") != "non_pv_scout_beta_only":
        raise ExportError("unsupported node class")

    pairs: list[tuple[int, int]] = []
    for row in rows:
        pair = (int(row["deep_depth"]), int(row["shallow_depth"]))
        if pair not in pairs:
            pairs.append(pair)
    maximum_probes = int(require_same(rows, "validated_maximum_probes_per_node"))
    if maximum_probes <= 0 or maximum_probes > len(pairs):
        raise ExportError("validated probe cap is inconsistent with pair order")

    evidence: list[list[str]] = []
    for record in require_same(rows, "scheduler_domain_evidence").split(";"):
        fields = record.split(":")
        if len(fields) != 15 or fields[3] not in MODE_CPP:
            raise ExportError(f"invalid scheduler evidence: {record}")
        evidence.append(fields)

    output = [
        "// Generated by tools/search-calibration/export_probcut_profile_cpp.py.",
        "// Do not edit by hand; regenerate from the reviewed profile TSV.",
        "#pragma once",
        "",
        "#include \"vibe_othello/search/probcut.h\"",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace vibe_othello::search::production_internal {",
        "",
        f"inline constexpr std::string_view kWeightsChecksum = {json.dumps(weights_checksum)};",
        f"inline constexpr Score kMaximumMargin = {maximum_margin};",
        f"inline constexpr double kMaximumShallowOverheadRatio = {cpp_float(str(maximum_overhead))};",
        "",
        f"inline constexpr std::array<ProbCutDepthPairV1, {len(pairs)}> kPairOrder{{{{",
    ]
    for deep, shallow in pairs:
        output.append(
            f"    ProbCutDepthPairV1{{.deep_depth = {deep}, .shallow_depth = {shallow}}},"
        )
    output.extend(
        [
            "}};",
            "",
            f"inline constexpr std::array<ProbCutSchedulerEvidenceV1, {len(evidence)}> "
            "kSchedulerEvidence{{",
        ]
    )
    for fields in evidence:
        output.extend(
            [
                "    ProbCutSchedulerEvidenceV1{",
                f"        .pair_prefix_length = {fields[0]},",
                f"        .maximum_probes_per_node = {fields[1]},",
                f"        .phase = {fields[2]},",
                f"        .search_mode = {MODE_CPP[fields[3]]},",
                f"        .minimum_empties = {fields[4]},",
                f"        .maximum_empties = {fields[5]},",
                f"        .deep_depth = {fields[6]},",
                f"        .exact_handoff_enabled = {cpp_bool(fields[7])},",
                f"        .exact_handoff_threshold = {fields[8]},",
                f"        .minimum_exact_handoff_distance = {fields[9]},",
                f"        .maximum_exact_handoff_distance = {fields[10]},",
                f"        .holdout_node_count = {fields[11]},",
                f"        .false_cut_count = {fields[12]},",
                f"        .cut_candidate_count = {fields[13]},",
                f"        .false_cut_rate_upper_bound = {cpp_float(fields[14])},",
                "    },",
            ]
        )
    output.extend(
        [
            "}};",
            "",
            f"inline constexpr std::array<ProbCutCalibrationEntryV1, {len(rows)}> kEntries{{{{",
        ]
    )
    for row in rows:
        mode = MODE_CPP.get(row["search_mode"])
        if mode is None:
            raise ExportError(f"invalid search mode: {row['search_mode']}")
        output.extend(
            [
                "    ProbCutCalibrationEntryV1{",
                f"        .phase = {int(row['phase'])},",
                f"        .search_mode = {mode},",
                f"        .minimum_empties = {int(row['minimum_empties'])},",
                f"        .maximum_empties = {int(row['maximum_empties'])},",
                f"        .deep_depth = {int(row['deep_depth'])},",
                f"        .shallow_depth = {int(row['shallow_depth'])},",
                f"        .exact_handoff_enabled = {cpp_bool(row['exact_handoff_enabled'])},",
                f"        .exact_handoff_threshold = {int(row['exact_handoff_threshold'])},",
                f"        .minimum_exact_handoff_distance = {int(row['minimum_exact_handoff_distance'])},",
                f"        .maximum_exact_handoff_distance = {int(row['maximum_exact_handoff_distance'])},",
                f"        .regression_slope = {cpp_float(row['regression_slope'])},",
                f"        .intercept = {cpp_float(row['intercept'])},",
                f"        .residual_sigma = {cpp_float(row['residual_sigma'])},",
                f"        .confidence_multiplier = {cpp_float(row['confidence_multiplier'])},",
                f"        .minimum_shallow_score = {int(row['minimum_shallow_score'])},",
                f"        .maximum_shallow_score = {int(row['maximum_shallow_score'])},",
                f"        .minimum_beta = {int(row['minimum_beta'])},",
                f"        .maximum_beta = {int(row['maximum_beta'])},",
                "    },",
            ]
        )
    output.extend(
        [
            "}};",
            "",
            "inline constexpr ProbCutCalibrationProfileV1 kProfile{",
            "    .schema_version = kProbCutCalibrationProfileSchemaVersion,",
            f"    .profile_id = {json.dumps(require_same(rows, 'profile_id'))},",
            "    .source_calibration_report_checksum_sha256 =",
            f"        {json.dumps(require_same(rows, 'source_checksum_sha256'))},",
            f"    .evaluator_family = {json.dumps(require_same(rows, 'evaluator_family'))},",
            f"    .artifact_family = {json.dumps(require_same(rows, 'artifact_family'))},",
            "    .node_class = ProbCutNodeClassV1::non_pv_scout_beta_only,",
            "    .validated_pair_order = kPairOrder,",
            f"    .validated_maximum_probes_per_node = {maximum_probes},",
            "    .joint_holdout_checksum_sha256 =",
            f"        {json.dumps(require_same(rows, 'joint_holdout_checksum_sha256'))},",
            f"    .joint_false_cut_count = {int(require_same(rows, 'joint_false_cut_count'))},",
            f"    .joint_cut_candidate_count = {int(require_same(rows, 'joint_cut_candidate_count'))},",
            "    .joint_false_cut_rate_upper_bound =",
            f"        {cpp_float(require_same(rows, 'joint_false_cut_rate_upper_bound'))},",
            "    .scheduler_evidence = kSchedulerEvidence,",
            "    .entries = kEntries,",
            "};",
            "",
            "} // namespace vibe_othello::search::production_internal",
            "",
        ]
    )
    return "\n".join(output)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("profile", type=Path)
    parser.add_argument("--weights-checksum", required=True)
    parser.add_argument("--maximum-margin", type=int, required=True)
    parser.add_argument("--maximum-shallow-overhead-ratio", type=float, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    if args.maximum_margin <= 0 or args.maximum_shallow_overhead_ratio <= 0.0:
        parser.error("runtime safety limits must be positive")
    try:
        rendered = render(
            args.profile,
            args.weights_checksum,
            args.maximum_margin,
            args.maximum_shallow_overhead_ratio,
        )
        args.output.write_text(rendered, encoding="utf-8")
    except (ExportError, OSError, ValueError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
